services:
 app:
    container_name: MM-Dashboard
    image: stubble1749/minecraft-manager
    ports:
      - "8000:8000"
    environment:
      - DISPLAY_SERVER_IP=some-ip # ip used in the dashboard to show users how to connect to their server
      - DJANGO_SUPERUSER_USERNAME=admin 
      - DEBUG=False # set to True for debugging
      - API_SERVER_PORT=5000 
      - SERVER=access-ip # optional: set this to access ip if not localhost
    volumes:
      - ./db:/app/db
    extra_hosts:
      - "host.docker.internal:host-gateway"  
